# generated by datamodel-codegen:
#   filename:  api.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr, Field, RootModel, conint, constr


class Model(RootModel[Any]):
    root: Any


class LoginRequest(BaseModel):
    email: EmailStr
    password: constr(min_length=1)


class NewPassword(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'(?=[A-Za-z])(?=\d)', min_length=10, max_length=200)


class ChangePassword(BaseModel):
    currentPassword: constr(min_length=1)
    newPassword: NewPassword


class Role(Enum):
    ADMIN = 'ADMIN'
    HR_OPS = 'HR_OPS'
    MANAGER = 'MANAGER'
    EMPLOYEE = 'EMPLOYEE'


class GrantAccess(BaseModel):
    role: Role


class UpdateAccess(BaseModel):
    role: Role | None = None
    isActive: bool | None = None


class DailyAttendanceQuery(BaseModel):
    date: date_aliased
    departmentId: UUID | None = None


class MonthlyAttendanceQuery(BaseModel):
    month: constr(pattern=r'^\d{4}-(0[1-9]|1[0-2])$')
    departmentId: UUID | None = None
    employeeId: UUID | None = None


class Status(Enum):
    PRESENT = 'PRESENT'
    HALF_DAY = 'HALF_DAY'
    ABSENT = 'ABSENT'


class ProposeCorrection(BaseModel):
    employeeId: UUID
    date: date_aliased
    status: Status
    checkIn: constr(pattern=r'^([01]\d|2[0-3]):[0-5]\d$') | None = None
    checkOut: constr(pattern=r'^([01]\d|2[0-3]):[0-5]\d$') | None = None
    reason: constr(min_length=1, max_length=500)


class ApproveCorrection(BaseModel):
    comment: constr(max_length=500) | None = None


class RejectCorrection(BaseModel):
    reason: constr(min_length=1, max_length=500)


class Status1(Enum):
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'


class CorrectionSearchQuery(BaseModel):
    page: conint(ge=1, le=9007199254740991) | None = 1
    pageSize: conint(ge=1, le=100) | None = 20
    status: Status1 | None = None
    employeeId: UUID | None = None


class EntityType(Enum):
    Employee = 'Employee'
    Department = 'Department'
    LeaveRequest = 'LeaveRequest'
    Document = 'Document'
    OnboardingTask = 'OnboardingTask'
    AttendanceRecord = 'AttendanceRecord'
    AttendanceCorrection = 'AttendanceCorrection'
    PolicyDocument = 'PolicyDocument'
    User = 'User'


class AuditSearchQuery(BaseModel):
    page: conint(ge=1, le=9007199254740991) | None = 1
    pageSize: conint(ge=1, le=100) | None = 20
    entityType: EntityType | None = None
    entityId: UUID | None = None
    actorId: UUID | None = None


class Category(Enum):
    LEAVE = 'LEAVE'
    ATTENDANCE = 'ATTENDANCE'
    CONDUCT = 'CONDUCT'
    ONBOARDING = 'ONBOARDING'
    BENEFITS = 'BENEFITS'
    PAYROLL = 'PAYROLL'
    IT_SECURITY = 'IT_SECURITY'
    OTHER = 'OTHER'


class PublishPolicy(BaseModel):
    title: constr(min_length=3, max_length=120)
    category: Category
    effectiveFrom: date_aliased
    summary: constr(max_length=500) | None = None


class CreateDepartment(BaseModel):
    name: constr(min_length=1, max_length=100)
    code: constr(pattern=r'^[A-Z0-9_-]{2,10}$')
    managerId: UUID | None = None


class Status2(Enum):
    ACTIVE = 'ACTIVE'
    ARCHIVED = 'ARCHIVED'


class UpdateDepartment(BaseModel):
    name: constr(min_length=1, max_length=100) | None = None
    code: constr(pattern=r'^[A-Z0-9_-]{2,10}$') | None = None
    managerId: UUID | None = None
    status: Status2 | None = None


class Type(Enum):
    OFFER_LETTER = 'OFFER_LETTER'
    ID_PROOF = 'ID_PROOF'
    ADDRESS_PROOF = 'ADDRESS_PROOF'
    PAN_CARD = 'PAN_CARD'
    BANK_DETAILS = 'BANK_DETAILS'
    EDUCATION_CERTIFICATE = 'EDUCATION_CERTIFICATE'
    EXPERIENCE_LETTER = 'EXPERIENCE_LETTER'
    PHOTO = 'PHOTO'
    OTHER = 'OTHER'


class UploadDocument(BaseModel):
    type: Type


class VerifyDocument(BaseModel):
    note: constr(max_length=500) | None = None


class FlagDocument(BaseModel):
    note: constr(min_length=1, max_length=500)


class Status3(Enum):
    PENDING = 'PENDING'
    VERIFIED = 'VERIFIED'
    FLAGGED = 'FLAGGED'


class DocumentSearchQuery(BaseModel):
    page: conint(ge=1, le=9007199254740991) | None = 1
    pageSize: conint(ge=1, le=100) | None = 20
    employeeId: UUID | None = None
    status: Status3 | None = None
    type: Type | None = None


class EmploymentType(Enum):
    FULL_TIME = 'FULL_TIME'
    PART_TIME = 'PART_TIME'
    CONTRACT = 'CONTRACT'
    INTERN = 'INTERN'


class Status4(Enum):
    ACTIVE = 'ACTIVE'
    PROBATION = 'PROBATION'


class CreateEmployee(BaseModel):
    firstName: constr(min_length=1, max_length=100)
    lastName: constr(min_length=1, max_length=100)
    email: EmailStr
    phone: constr(max_length=50) | None = None
    dateOfBirth: date_aliased | None = None
    jobTitle: constr(min_length=1, max_length=150)
    departmentId: UUID
    managerId: UUID | None = None
    location: constr(min_length=1, max_length=100)
    joiningDate: date_aliased
    employmentType: EmploymentType
    status: Status4 | None = 'PROBATION'


class UpdateEmployee(BaseModel):
    firstName: constr(min_length=1, max_length=100) | None = None
    lastName: constr(min_length=1, max_length=100) | None = None
    email: EmailStr | None = None
    phone: constr(max_length=50) | None = None
    dateOfBirth: date_aliased | None = None
    jobTitle: constr(min_length=1, max_length=150) | None = None
    departmentId: UUID | None = None
    managerId: UUID | None = None
    location: constr(min_length=1, max_length=100) | None = None
    joiningDate: date_aliased | None = None
    employmentType: EmploymentType | None = None
    status: Status4 | None = 'PROBATION'
    version: conint(ge=1, le=9007199254740991)


class ArchiveEmployee(BaseModel):
    version: conint(ge=1, le=9007199254740991)
    reason: constr(max_length=500) | None = None


class Status6(Enum):
    ACTIVE = 'ACTIVE'
    PROBATION = 'PROBATION'
    ARCHIVED = 'ARCHIVED'


class EmployeeSearchQuery(BaseModel):
    page: conint(ge=1, le=9007199254740991) | None = 1
    pageSize: conint(ge=1, le=100) | None = 20
    q: constr(max_length=100) | None = None
    departmentId: UUID | None = None
    managerId: UUID | None = None
    location: constr(max_length=100) | None = None
    status: Status6 | None = None


class Type2(Enum):
    ANNUAL = 'ANNUAL'
    SICK = 'SICK'
    CASUAL = 'CASUAL'
    UNPAID = 'UNPAID'


class CreateLeaveRequest(BaseModel):
    employeeId: UUID | None = None
    type: Type2
    startDate: date_aliased
    endDate: date_aliased
    reason: constr(max_length=500) | None = None


class ApproveLeave(BaseModel):
    comment: constr(max_length=500) | None = None


class RejectLeave(BaseModel):
    reason: constr(min_length=1, max_length=500)


class View(Enum):
    mine = 'mine'
    approvals = 'approvals'
    all = 'all'


class Status7(Enum):
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    CANCELLED = 'CANCELLED'


class LeaveSearchQuery(BaseModel):
    page: conint(ge=1, le=9007199254740991) | None = 1
    pageSize: conint(ge=1, le=100) | None = 20
    view: View | None = 'all'
    employeeId: UUID | None = None
    status: Status7 | None = None
    type: Type2 | None = None
    from_: date_aliased | None = Field(None, alias='from')
    to: date_aliased | None = None


class LeaveBalanceQuery(BaseModel):
    year: conint(ge=2000, le=2100) | None = None


class Status8(Enum):
    PENDING = 'PENDING'
    DONE = 'DONE'
    SKIPPED = 'SKIPPED'


class UpdateOnboardingTask(BaseModel):
    status: Status8 | None = None
    notes: constr(max_length=1000) | None = None
    dueDate: date_aliased | None = None


class State(Enum):
    active = 'active'
    completed = 'completed'
    all = 'all'


class OnboardingSearchQuery(BaseModel):
    page: conint(ge=1, le=9007199254740991) | None = 1
    pageSize: conint(ge=1, le=100) | None = 20
    state: State | None = 'active'


class PayrollReportQuery(BaseModel):
    month: constr(pattern=r'^\d{4}-(0[1-9]|1[0-2])$')
