/**
 * Object storage for uploaded files. Keys are generated by the API, never by
 * clients. Local disk in development; an S3-compatible driver (Supabase
 * Storage) replaces it in deployment.
 */
export abstract class StorageService {
  abstract put(key: string, data: Buffer, contentType: string): Promise<void>;
  abstract read(key: string): Promise<Buffer>;
  abstract delete(key: string): Promise<void>;
}
